# Generated by Django 4.2.6 on 2023-10-28 21:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authors', '0005_author_followers'),
    ]

    operations = [
        migrations.CreateModel(
            name='Like',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('@context', models.CharField(default='https://www.w3.org/ns/activitystreams', max_length=200)),
                ('summary', models.CharField(max_length=200)),
                ('type', models.CharField(default='Like', max_length=50)),
                ('object', models.URLField()),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authors.author')),
            ],
        ),
    ]
