# Generated by Django 4.2.6 on 2023-10-14 00:43

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type', models.CharField(default='author', max_length=50)),
                ('id', models.URLField(unique=True)),
                ('host', models.URLField()),
                ('display_name', models.CharField(max_length=100)),
                ('url', models.URLField(unique=True)),
                ('github', models.URLField(blank=True)),
                ('profile_image', models.URLField(blank=True, max_length=100)),
            ],
        ),
    ]
