# Generated by Django 4.2.6 on 2023-10-14 01:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authors', '0003_alter_author_host'),
    ]

    operations = [
        migrations.RenameField(
            model_name='author',
            old_name='display_name',
            new_name='displayName',
        ),
        migrations.RenameField(
            model_name='author',
            old_name='profile_image',
            new_name='profileImage',
        ),
    ]
