# Generated by Django 4.2.6 on 2023-10-26 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authors', '0004_rename_display_name_author_displayname_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='email',
            field=models.EmailField(blank=True, max_length=100, unique=True),
        ),
    ]
