# Generated by Django 4.2.6 on 2023-10-26 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authors', '0004_rename_display_name_author_displayname_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='followers',
            field=models.ManyToManyField(blank=True, to='authors.author'),
        ),
    ]
