# Generated by Django 4.2.6 on 2023-10-26 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authors', '0005_author_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='username',
            field=models.CharField(default='username', max_length=50, unique=True),
        ),
    ]
