# Generated by Django 4.2.6 on 2023-10-29 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authors', '0005_author_followers'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='inbox',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
