# Generated by Django 4.2.6 on 2023-10-30 01:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authors', '0006_remove_author_id_author_followers_author_groups_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='id',
            field=models.URLField(editable=False, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='author',
            name='url',
            field=models.URLField(editable=False, unique=True),
        ),
    ]
