# Generated by Django 4.2.6 on 2023-10-30 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authors', '0007_author_id_alter_author_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='inbox',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
