# Generated by Django 4.2.6 on 2023-11-15 18:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authors', '0008_author_inbox'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='author',
            name='inbox',
        ),
    ]
