# Generated by Django 4.2.6 on 2023-10-26 10:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authors', '0009_author_displayname'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='author',
            name='id',
        ),
    ]
