# Generated by Django 4.2.6 on 2023-10-26 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authors', '0011_alter_author_uuid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='author',
            name='username',
        ),
        migrations.AlterField(
            model_name='author',
            name='displayName',
            field=models.CharField(default='displayName', max_length=100, unique=True),
        ),
    ]
