# Generated by Django 4.2.7 on 2023-11-29 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authors', '0011_alter_author_host_alter_author_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='uuid',
            field=models.CharField(editable=False, primary_key=True, serialize=False),
        ),
    ]
