# Generated by Django 4.2.7 on 2023-12-06 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authors', '0012_alter_author_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='profileImage',
            field=models.URLField(blank=True, max_length=250),
        ),
    ]
