# Generated by Django 4.2.6 on 2023-10-26 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authors', '0012_remove_author_username_alter_author_displayname'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='id',
            field=models.CharField(default='', editable=False, max_length=100, unique=True),
        ),
    ]
