# Generated by Django 4.2.6 on 2023-10-26 23:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authors', '0014_alter_author_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='author',
            name='id',
        ),
    ]
