# Generated by Django 4.2.6 on 2023-10-27 00:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authors', '0015_remove_author_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='id',
            field=models.CharField(default='', editable=False, max_length=100, unique=True),
        ),
    ]
