# Generated by Django 4.2.6 on 2023-10-27 00:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authors', '0016_author_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='author',
            name='id',
        ),
    ]
