# Generated by Django 4.2.6 on 2023-10-27 00:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authors', '0019_alter_author_uuid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='author',
            name='email',
        ),
    ]
