# Generated by Django 4.2.6 on 2023-10-27 00:57

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('authors', '0020_remove_author_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='id',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='author',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
