# Generated by Django 4.2.6 on 2023-10-20 03:59

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authors', '0004_rename_display_name_author_displayname_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type', models.CharField(default='post', max_length=200)),
                ('title', models.CharField(max_length=200)),
                ('source', models.URLField()),
                ('origin', models.URLField()),
                ('description', models.CharField(max_length=200)),
                ('contentType', models.CharField(max_length=200)),
                ('content', models.TextField()),
                ('categories', models.JSONField()),
                ('count', models.IntegerField()),
                ('comments', models.URLField()),
                ('published', models.DateTimeField()),
                ('visibility', models.CharField(max_length=255)),
                ('unlisted', models.BooleanField()),
                ('commentsSrc', models.JSONField(blank=True, null=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authors.author')),
            ],
        ),
    ]
