# Generated by Django 4.2.6 on 2023-11-19 20:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0002_alter_post_author_alter_post_origin_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='commentsSrc',
        ),
    ]
