# Generated by Django 4.2.6 on 2023-11-26 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0003_remove_post_commentssrc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='comments',
            field=models.URLField(blank=True, null=True),
        ),
    ]
