# Generated by Django 4.2.6 on 2023-11-15 22:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('followers', '0001_initial'),
        ('post', '0002_alter_post_author_alter_post_origin_and_more'),
        ('likes', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Inbox',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(default='inbox', max_length=50)),
                ('author', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('follows', models.ManyToManyField(blank=True, to='followers.follow')),
                ('likes', models.ManyToManyField(blank=True, to='likes.like')),
                ('posts', models.ManyToManyField(blank=True, to='post.post')),
            ],
        ),
    ]
